### ISSUE TITLE
Guestbook posting is broken

### ISSUE THREAD

**Issue by HIDEN64** [HIDEN64/hidens-website#20]
This issue seems to be in part by the middleware handler (which was added to fix banning behind a reverse proxy)

Here's a capture of the error:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\Users\Anna\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\Anna\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\Anna\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\Projects\Programming\Websites\hiden.pw\site_ctrl.py", line 18, in middleware_handler
    return await handler(request)
  File "D:\Projects\Programming\Websites\hiden.pw\site_ctrl.py", line 463, in gb_submission_handler
    add_entry(req.remote, name, email, location, website, message)
TypeError: add_entry() missing 1 required positional argument: 'message
```

I'm not sure why it's doing this. Any help would be greatly appreciated.

OS: Windows 10 Enterprise v22H2
Browser: LibreWolf 112.0.1-2
Python version: 3.6
settings_local.py file:
```
PORT = 80
ENABLE_LOGGING = True
LOG_TO_FILE = False
DEV_MODE = True
SERVE_STATIC = True
SERVE_STORAGE = True
SERVE_JS = True
```

**Comment by HIDEN64** [comment]
A temporary, yandev-ey workaround was implemented in [adc315e](https://github.com/HIDEN64/hidens-website/commit/adc315e59119005f529f40d278c6e948a376fe59). I'll use this for now until a proper fix is implemented.
